# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM node:alpine

COPY . .

RUN npm i -omit=dev

RUN npx prisma generate

EXPOSE 8000
ENTRYPOINT [ "node", "index.js" ]
