# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1

COPY . .
COPY ./prisma prisma

RUN bun install

RUN bun run prisma

EXPOSE 8000
ENTRYPOINT [ "bun", "run", "prisma", "&&", "bun", "run", "start" ]
