name: app-action

on:
  push:
    paths:
      - 'app/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
      - name: installing package
        working-directory: ./app
        run: flutter pub get
      - name: checking errors
        working-directory: ./app
        run: flutter analyze
      - name: running test
        working-directory: ./app
        run: flutter test
