name: app-action

on:
  push:
    paths:
      - 'app/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'       

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./app

      - name: Analyze code
        run: flutter analyze
        working-directory: ./app

      - name: Run tests
        run: flutter test
        working-directory: ./app
