name: server-action

on:
  push:
    paths:
      - 'server/**'

jobs:
  validate:
    name: validate-code-and-linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies and lint code
        working-directory: ./server
        run: |
          bun install
          bun run lint
          bun run test

